services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  fastapi:
    build: ./whitefly_fastapi
    volumes:
      - ./whitefly_fastapi:/app
    ports:
      - "8000:8000"

  celery:
    build: ./whitefly_fastapi
    command: celery -A app.services.celery worker --loglevel=info
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis

  nginx:
    build: ./nginx
    volumes:
      - .:/app
    ports:
      - "80:80"